# Generated by Django 4.1.5 on 2023-01-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airpollution',
            old_name='body',
            new_name='data',
        ),
    ]
